apiVersion: k3d.io/v1alpha2
kind: Simple
name: smrcluster
servers: 1
agents: 2
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6445"
image: rancher/k3s:v1.20.4-k3s1
volumes:
  - volume: /coit-skaffold/projects
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
